### PR TITLE
Add Windows build

### PR DESCRIPTION
**Pull request by kozo2**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @kozo2 - can you please merge from master and rerender? Thanks!

**Comment by kozo2** [comment]
@scopatz Thank you for your comment. I merged from master and rerendered.
However, I can not include the build artifact gvim.exe into the package.
How should I modify the meta.yaml for it?
gvim.exe is created https://github.com/vim/vim/tree/master/src in the source code.

**Comment by bdice** [comment]
@kozo2 Thank you for your work on this. I would be very happy to have a Windows build of vim, even without gvim. Would you be willing to consider re-rendering and seeking review/merge on this pull request with only vim and no GUI application? The GUI could be added later. If you don't have time, I could make a new PR based on your starting work that is up to date.

**Comment by kozo2** [comment]
@bdice Thank you for your suggestion. I only know how to build the GUI vim described in https://github.com/vim/vim-win32-installer/blob/master/appveyor.bat .
So I can not live up to the expectations of building no GUI vim.
Please use your PR to contribute to conda-forge. Also, please let me know if I should close this PR.

**Comment by bdice** [comment]
@kozo2 Okay, thanks for the info! I appreciate your effort and I will consider making a new PR when I have some time (or need a break from other work 😊).

**Comment by matthiasdiener** [comment]
Closing since this was done in #1595.

**Pull request closed without merging**
