### PR TITLE
Fix pythoninterp py3k support.

### PR DESCRIPTION
**Pull request by asford**
Fix `--enable-python[3]interp` flags in build.sh to support py3k. Fixes
python support in python3.6 and python3.7 builds.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by asford** [comment]
@conda-forge-admin, please rerender

**Comment by asford** [comment]
@mariusvniekerk Would you mind taking a look at this fix for python support? I'm happy to commit to maintaining this going forward.

**Comment by y0ast** [comment]
This would be a glorious addition. Thanks @asford !

**Comment by asford** [comment]
Friendly ping, @bgruening you've closed the last few pulls here. Can you take a look?

**Comment by asford** [comment]
Friendly ping, @scopatz @mariusvniekerk you're listed as the front-page maintainers on this recipe. Would you mind taking a look at this fix for python3 and vim? 

I'd be happy to join as a maintainer of this recipe!

**Comment by bgruening** [comment]
@conda-forge-admin, please re-render

**Comment by bgruening** [comment]
@aseyboldt sorry for the late reply. Please feel free to ping me harder, I get too many github notifications and sometimes they slip through the cracks.

**Comment by bgruening** [comment]
@asford I'm not an official maintainer of this repo, but I guess its fine if you create a PR and add yourself as maintainer. Thanks for the offer and your contribution!

**Pull request merged**
