### PR TITLE
add linux-{aarch64,ppc64le}

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Ready for review @conda-forge/vim

**Comment by matthiasdiener** [comment]
Ready for review @conda-forge/vim @conda-forge/core

**Comment by jakirkham** [comment]
Can you please add this to [the arch migrator]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt )?

**Comment by matthiasdiener** [comment]
> Can you please add this to [the arch migrator](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt)?

Added here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1933

**Comment by jakirkham** [comment]
> > Can you please add this to [the arch migrator](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt)?
> 
> Added here: [conda-forge/conda-forge-pinning-feedstock#1933](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1933)

Thanks! Merged :)

**Comment by matthiasdiener** [comment]
> > > Can you please add this to [the arch migrator](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt)?
> > 
> > 
> > Added here: [conda-forge/conda-forge-pinning-feedstock#1933](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1933)
> 
> Thanks! Merged :)

Thanks! Conda-forge will open a new PR automatically and this PR can be closed, right?

**Pull request merged**
